name: flutter_axios
description: A promise-based HTTP client for Flutter inspired by Axios. Provides interceptors, request/response transformation, error handling, and more.
version: 1.0.0
homepage: https://github.com/yourusername/flutter_axios

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
